#+TITLE: "「ご注意：この記事の全部または一部を転載される場合は事前に連絡の上，承諾を得てからでお願いします。」という深澤諭史弁護士のブログ記事"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-09-17 09:09:50 +0900
FILE_NAME: 2019-09-17-090950_「ご注意：この記事の全部または一部を転載される場合は事前に連絡の上，承諾を得てからでお願いします。」という深澤諭史弁護士のブログ記事.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士 ,名誉毀損
記事タイトル名の文字数：66　保存ファイル名の文字数：88

* 「ご注意：この記事の全部または一部を転載される場合は事前に連絡の上，承諾を得てからでお願いします。」という深澤諭史弁護士のブログ記事

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 名誉毀損

* 「ご注意：この記事の全部または一部を転載される場合は事前に連絡の上，承諾を得てからでお願いします。」という深澤諭史弁護士のブログ記事
<div style="color: #708090; font-size: 11px;">
  :LOGBOOK:
  CLOCK: [2019-09-16 月 12:08]--[2019-09-16 月 14:58] =>  2:50
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: Twitter,名誉毀損
</div><hr />

＞＞＞ 2019-09-16（月曜日）12：08 ＞＞＞

　取り上げようかどうか迷っていたのですが、さきほど次の深澤諭史弁護士のツイートを深澤諭史弁護士のタイムラインで見かけたことで決めました。その前にも一つ気になるリツイートを見かけていました。嶋﨑量弁護士の深澤諭史弁護士の当該記事を評価したツイートになります。

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/09/15 19:54 URL： https://twitter.com/fukazawas/status/1173188265509146626
> 「リツイートは賛同で責任を負う」と報道された判決の判決文を読んでみた - 弁護士 深澤諭史のブログ https://t.co/LVRjWlRUmq  \n 未だにアクセスが膨大で、驚き（；・∀・）
▷▷▷　　　　　End　　　　　▷▷▷

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/09/13 18:11 URL： https://twitter.com/fukazawas/status/1172437534871191552
> 「リツイートは賛同で責任を負う」と報道された判決の判決文を読んでみた : 弁護士 深澤諭史のブログ https://t.co/LVRjWlRUmq \n ということで、難しかったけど、解説しました。
▷▷▷　　　　　End　　　　　▷▷▷

　深澤諭史弁護士のTwitter運用の特徴として、自身のツイートのリツイートを何度か繰り返しているようですが、9月13日18時11分の上記のツイートは、今現在でリツイートが331件、いいねが277件となっています。

　深澤諭史弁護士が「未だにアクセスが膨大で、驚き（；・∀・）」というのは、ブログのアクセス数のことかと思われます。一月ほど経ったでしょうか、深澤諭史弁護士のツイートで1万に近いリツイートや、1万件を超える「いいね」のツイートがありました。

<span style="color: #01DFA5; font-size: 12px;">» @fukazawasの分析 - whotwi グラフィカルTwitter分析 https://t.co/fkwVnS7alR</span>

　特定のアカウントのツイートで最もリツイートの数が多いツイートというのも情報として以前見かけたように思うのですが、上記のサイトではそれらしい情報は見かけませんでした。

```
＊************************** 5. row ***************************
             id: 375654
           name: 深澤諭史
        rt_name: 
         tw_url: https://twitter.com/fukazawas/status/1154957973749239809
         rt_url: 
        tw_date: 2019-07-27 12:33:00
        rt_date: 1000-01-01 00:00:00
          tweet: ＊弁護士から見た嘘をついている人の言動の特徴＊
①質問と答えが一致しない。
②端的に答えずに，前提とか動機とか，聞かれもしない理由付けを延々と話す。
③他ならぬ「自分の行動と記憶」を質問されているのに，なぜか「普通の人」の話をする。
続く
      org_tweet: 
        retweet: 0
           user: fukazawas
 statuses_count: 91003
        rt_user: 
    create_time: 2019-07-27 17:30:31
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。 詳しくは、 IT法務.jp もご覧下さい。相談等ご依頼はTwitterでなく事務所あるいはブログ掲載のメールアドレスまで。
            app: Twitter Web App
       location: 東京
followers_count: 5762
  friends_count: 491
       rt_count: 727
      fav_count: 1410
            tag: nil
```

　上記が自分のデータベースで探し出した深澤諭史弁護士のツイートになります。次のコマンドを実行した結果の一部になります。

```
mysql -u root benngosi_twitter -e 'SELECT * FROM tw_user_tweet WHERE user LIKE "fukazawas" AND tweet LIKE "%弁護士から見た嘘をついている人の言動の特徴%"  order by rt_count limit 6\G'
```

　データベースに記録したツイートのリツイート数は、データベース登録時のものになります。そのことを失念していたため、リツイート数の上位に該当がありませんでした。結局、自分のTwilogから探す出すことが出来たのですが、それが次のツイートになります。

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW fukazawas（深澤諭史） 日時：2019/07/27 12:33 URL： https://twitter.com/fukazawas/status/1154957973749239809
> ＊弁護士から見た嘘をついている人の言動の特徴＊ \n ①質問と答えが一致しない。 \n ②端的に答えずに，前提とか動機とか，聞かれもしない理由付けを延々と話す。 \n ③他ならぬ「自分の行動と記憶」を質問されているのに，なぜか「普通の人」の話をする。 \n 続く
▷▷▷　　　　　End　　　　　▷▷▷

　リツイート数は、2019年9月16日13時39分の時点で8,072件、いいねは2万件と表示されています。さきほどスクリーンショットを記録したのですが、たぶんリツイート数に変動はないものと思われます。

　時刻は13時46分です。テレビはバイキングが終わり、グッディが始まりました。昼前、北陸中日新聞のテレビ欄に、バイキングの放送内容としてトップに、紀州のドンファンが13億超え田辺市に寄付などとあったのですが、今日の放送にそれらしいものは見なかったと思います。

　不審死が疑われた紀州のドンファンの問題ですが、話題を見たのもずいぶん久しぶりでした。ネットでも情報は見かけていませんが、放送内容が変更になったのだとすれば、新聞のテレビ欄との齟齬というのはたぶん初めてみた珍しいものでした。

　ずっとテレビの前にいたわけではなく、台所でベーコンと目玉焼きで昼食を食べていたのですが、大きな羽音のスズメバチが近寄ってきて、ご飯を食べていた丼の中に落下して、それからすぐに姿を消しました。

　スズメバチが家の中に入ってきたことはこれまでに何度かあり、それも夜が多かったのですが、今回のスズメバチは余り大きくない割に羽音が聞いたことがないぐらいに大きく、けたたましく不気味な音が近づいてくるのになかなか姿が見つかりませんでした。

　「リツイートは賛同で責任を負う」というニュースですが、深澤諭史弁護士の関連ツイートやブログの内容を見たところ当事者の情報は見当たらなかったと思うのですが、他に見た情報によると一方の当事者が橋下徹弁護士となっていたと思います。

```
１２日、大阪地裁であった。末永雅之裁判長は「元の投稿をそのまま引用するリツイートは、その内容に賛同する表現行為で責任を負う」と認定し、男性に３３万円の支払いを命じた。

　男性は橋下氏側の提訴前に当該リツイートを削除していたが、末永裁判長はそうした事情を踏まえても、名誉毀損で慰謝料が認められるとした。

　男性はインターネットメディア「インディペンデント・ウェブ・ジャーナル」代表の岩上安身氏。判決によると、岩上氏は平成２９年１０月、橋下氏が府知事時代に部下の府幹部を自殺に追い込んだ、とする第三者の投稿をリツイートした。岩上氏は同年１２月までにリツイートを削除した。

<span style="color: #01DFA5; font-size: 12px;">［source：］ 中傷のツイート転載で名誉毀損　橋下徹氏の訴え認める　大阪地裁 - 産経ニュース <a href="https://www.sankei.com/west/news/190912/wst1909120027-n1.html">https://www.sankei.com/west/news/190912/wst1909120027-n1.html</a></span>
```

　確認の必要もあるので調べたところ、33万円の支払い判決ということで、前に見た情報よりは金額が多いように感じました。さらに敗訴した側が、岩上安身氏というのも意外でした。これもそれらしい人物の情報は見かけていたのですが、岩上氏という私の認識はこれまで皆無でした。

　岩上安身氏のツイートをよく見かけていたのはPC遠隔操作事件の頃だったと思います。最近はほとんどツイートを見かけることもなく存在自体も忘れかけていました。

　岩上安身氏のことで最も強く印象にあるのは、小学生の低学年ぐらいの子どもと生活しているという情報を見かけたことで、これはその後に知った東京新聞の女性記者にも共通していたのですが、その女性記者の名前も思い出せません。注目を集め活発な活動がありました。

<span style="color: #01DFA5; font-size: 12px;">» 東京新聞　女性記者 - Google 検索 https://t.co/3ClW7ohDVu</span>

<span style="color: #01DFA5; font-size: 12px;">» 東京新聞・望月記者を恐れる官邸　いま政治取材の現場で起きている「異常事態」とは (1/3) 〈dot.〉｜AERA dot. (アエラドット) https://t.co/OtRUReTKAx</span>

　なにか映画のことも話題になっていました。望月衣塑子記者でしたが、ネットの情報だけで、まだテレビで姿を見かけたことはないような気もします。東京新聞といえば、その名前とは意外に中日新聞の子会社という情報を見かけたことがありました。10年ほど前かと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ISOKO_MOCHIZUKI（望月衣塑子） 日時：2019-09-16 14:17／2019/06/29 12:07 URL： https://twitter.com/kk_hirono/status/1173465900072108032 https://twitter.com/ISOKO_MOCHIZUKI/status/1144804651574820864
> 映画 「 #新聞記者 」が全国150館で上映スタート！  萎縮や忖度が蔓延し、時に息苦しさ感じる日本社会の中で、一人一人がどう直面する問題に向き合い、声を上げ社会を変えていけるのか。映画を観た方々が一歩を踏み出す勇気を持って頂けた… https://t.co/iZin8gDEDT
▶▶▶　　　　　End　　　　　▶▶▶

　望月といえば、望月弁護士がいて、ここ半月ほどの間に3回ほど思い出して、芸能人の大麻事件で判決期日が延期になった件で、その後どうなっているのか確認しておきたいと思いながら、未だやっていなかったことを思い出しました。

　これまでに何度か書いてきたと思いますが、この9月の前半は、ずいぶん久しぶりにテレビをつける、テレビを見る時間がとても少ない生活でした。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜166mochizuki（望月宣武 Hiromu MOCHIZUKI） 日時：2019-09-16 14:26／2019/08/08 22:04 URL： https://twitter.com/kk_hirono/status/1173468174534107136 https://twitter.com/166mochizuki/status/1159450283346259968
> 私のツイートが不誠実であるとのご指摘をいただきました。ご指摘ありがとうございます。当該ツイートは、嫌がらせを繰り返しているアカウントに対してなので、誠実さを欠いた内容かもしれません。そのような背景をご存知ない方には不誠実に見えると… https://t.co/xXFb7bpuz4
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜166mochizuki（望月宣武 Hiromu MOCHIZUKI） 日時：2019-09-16 14:25／2019/09/13 17:32 URL： https://twitter.com/kk_hirono/status/1173467829334446080 https://twitter.com/166mochizuki/status/1172427738558296064
> 報道関係者も含めた抽選にするって、弁護士会関係者で傍聴席を埋める作戦かしら。 ちなみに、裁判所は通常、国民の知る権利に資するために、マスコミ傍聴席を設けています。 https://t.co/5YV8lijUVh
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜166mochizuki（望月宣武 Hiromu MOCHIZUKI） 日時：2019-09-16 14:24／2019/09/16 09:05 URL： https://twitter.com/kk_hirono/status/1173467658190090240 https://twitter.com/166mochizuki/status/1173387397544861696
> ある警察の不祥事があって、明日にでも罪を犯した警察官を逮捕して捜査すると聞いてますけど、もし警察が内部でもみ消す方向に行くなら、私から公表に動く所存。
▶▶▶　　　　　End　　　　　▶▶▶

166mochizuki ===> You have already retweeted this Tweet.
▷▷▷　@kk_hironoでリツイート済みのツイートです。　▷▷▷
RT 166mochizuki（望月宣武 Hiromu MOCHIZUKI） 日時：2019/08/07 18:22 URL： https://twitter.com/166mochizuki/status/1159031934065864705
> 例の件で進捗ないものかと気になって検察官に電話したら、裁判所の夏季休廷に合わせて休暇を取っていらっしゃった。みんな、休めるときに休みましょう。
▷▷▷　　　　　End　　　　　▷▷▷

　どうも進捗はないようです。判決が延期された理由も謎のままですが、無罪になりかねないような検察のミスという話も出ていて、それがテレビにも流れていました。

```
望月宣武 Hiromu MOCHIZUKI
@166mochizuki
弁護士、東京弁護士会、東京。静岡県清水市出身、東京大学法学部・ヨット部卒。日本羅針盤法律事務所 代表。日本エンターテイナーライツ協会（ERA）共同代表理事。東京大学三四郎会 会長。（社）リーガルファンディング 代表理事。（公財）日本セーリング連盟 参与。破産者マップ被害対策弁護団 団長。
Tokyofacebook.com/166mochizuki2013年9月からTwitterを利用しています
199 フォロー中
2,246 フォロワー

<span style="color: #01DFA5; font-size: 12px;">［source：］  望月宣武 Hiromu MOCHIZUKI（@166mochizuki）さんの返信があるツイート / Twitter <a href="https://twitter.com/166mochizuki/with_replies">https://twitter.com/166mochizuki/with_replies</a></span>
```

　望月宣武弁護士はTwitterの更新が少ないようですが、深澤諭史弁護士に似た不思議な存在感があります。ブロックしたとかされたとかいう他のアカウントとのやりとりも見かけていましたが、深澤諭史弁護士ほど大きなリツイートも見ていない気がします。

　今のところ深澤諭史弁護士の姿をテレビで見かけたことはないのですが、テレビ番組の出演もやっているようです。

　望月宣武弁護士の場合、愛媛の農業アイドル自殺問題で記者会見をする姿を何度も見かけていましたが、不思議と知名度が少ないというか世間の関心が乏しいように思われます。

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜166mochizuki（望月宣武 Hiromu MOCHIZUKI） 日時：2019-09-16 14:43／2019/07/30 17:35 URL： https://twitter.com/kk_hirono/status/1173472456448757760 https://twitter.com/166mochizuki/status/1156121106312339457
> 裁判所が #小嶺麗奈 さんの勾留を取り消しました。もともと保釈中でしたので、釈放されている身柄に実質的な変更は無いのですが、本日の判決延期について裁判所から「小嶺さんには責任がない」と公に示してもらいたかったので、迅速かつ公正な判… https://t.co/z1Q5syRsrZ
▶▶▶　　　　　End　　　　　▶▶▶

　上記にリツイートをしたツイートも、リツイートが65件、いいねが87件という数です。「裁判所が #小嶺麗奈 さんの勾留を取り消しました。」とハッシュタグまで付いていますし、テレビで繰り返し放送されていた事件でした。

　望月宣武弁護士においては、愛媛のアイドル自殺問題でクラウドファンディングを行い、一部、訴えを取り下げたことなどで一部に不信を買って、それがブロックという対応にもなったようですが、特に調べてもいないので、望月弁護士以外の話はほとんど見かけていません。

　あらためて「ご注意：この記事の全部または一部を転載される場合は事前に連絡の上，承諾を得てからでお願いします。」という注意書きですが、批評をするにも前提としての引用が必要となりそうに考えますが、連絡の上承認を得てからというのは、どうなのかと思います。

　私の場合、３つのTwitterアカウントを深澤諭史弁護士にブロックされているので連絡をとるのも難しそうです。弁護士に対するリスペクトの要求というのも何かの前提条件のように深澤諭史弁護士のツイートでは見かけてきました。

　承認を得ないで引用した場合の罰則、不利益等にまで言及はありませんが、事実上の言論封圧があるようにも思えてなりません。地裁判決に対する一弁護士の論評にどれほどの価値があるのかも不明ですが、知的財産権の侵害のような感覚が弁護士の定番スタイルなのかとも考えます。

＜＜＜ 2019-09-16（月曜日）14：58 ＜＜＜


